// External Imports
import { Document, ObjectId } from 'mongoose';

/**
 * Interface for a Document that has a createdAt and updatedAt timestamp
 */
export interface TimestampedDocument extends Document {
	/**
	 * The ID Generated by MongoDB
	 */
	_id: ObjectId;

	/**
	 * The Date the Document was Created in the Database
	 */
	createdAt: Date;

	/**
	 * The Date the Document was Last Updated in the Database
	 */
	updatedAt: Date;
}
