[meta]
name = "Predictor"
author = "JackNytely"
category = "Utilities"
version = "3"
siteid = 160

[script]
dependencies = [ "MLHook", "VehicleState", "MLFeedRaceData" ]
optional_dependencies = ["DID"]

